#!/usr/bin/env python3

import time

# If all nodes launched by launch_test die before the tests are over, launch_test
# treats that like a test failure.  To allow testing in this situation, launch_testing_ros
# provides the empty_node which can be launched alongside the other nodes under test
# allowing them to terminate on their own without causing a test failure.


if __name__ == '__main__':

    try:
        while True:
            time.sleep(1 * 60 * 60 * 24)
    except KeyboardInterrupt:
        pass
